# Server Name
name: TinyPixel.us.to!

# Messages
# Tags: {amount}, {item}, {cost}, {missing}
messages:
  #Message sent when you buy an item
  bought: "You have bought {amount} {item} for ${cost}"
  not-enough-money: "You do not have enough money to buy {amount} {item}. You are missing ${missing}."

# Items in each shop category.
items:
  # Format for items is id:meta:amount:name:price:imgtype:imgpath (Note: imgtype and imgpath are optional. 0 is path, 1 is url)
  # For URLs, remove the : to prevent issues, the plugin will add it on its own.
  weapons:
    - "268:0:1:Wooden Sword:25:0:textures/items/wood_sword"
    - "272:0:1:Stone Sword:50:0:textures/items/stone_sword"
    - "267:0:1:Golden Sword:100:0:textures/items/gold_sword"
    - "283:0:1:Iron Sword:150:0:textures/items/iron_sword"
    - "276:0:1:Diamond Sword:250:0:textures/items/diamond_sword"
    - "261:0:1:Bow:20:0:textures/items/bow_standby"
    - "262:0:64:Arrow:30:0:textures/items/arrow"
  tools:
    - "278:0:1:Diamond Pickaxe:250:0:textures/items/diamond_pickaxe"
    - "285:0:1:Golden Pickaxe:150:0:textures/items/gold_pickaxe"
    - "257:0:1:Iron Pickaxe:200:0:textures/items/iron_pickaxe"
    - "274:0:1:Stone Pickaxe:50:0:textures/items/stone_pickaxe"
    - "270:0:1:Wooden Pickaxe:25:0:textures/items/wood_pickaxe"
  armor:
    - "310:0:1:Diamond Helmet:250:0:textures/items/diamond_helmet"
    - "311:0:1:Diamond Chestplate:250:0:textures/items/diamond_chestplate"
    - "312:0:1:Diamond Leggings:250:0:textures/items/diamond_leggings"
    - "313:0:1:Diamond Boots:250:0:textures/items/diamond_boots"
    - "302:0:1:Chain Helmet:150:0:textures/items/chainmail_helmet"
    - "303:0:1:Chain Chestplate:150:0:textures/items/chainmail_chestplate"
    - "304:0:1:Chain Leggings:150:0:textures/items/chainmail_leggings"
    - "305:0:1:Chain Boots:150:0:textures/items/chainmail_boots"
    - "306:0:1:Iron Helmet:170:0:textures/items/iron_helmet"
    - "307:0:1:Iron Chestplate:170:0:textures/items/iron_chestplate"
    - "308:0:1:Iron Leggings:170:0:textures/items/iron_leggings"
    - "309:0:1:Iron Boots:170:0:textures/items/iron_boots"
    - "314:0:1:Golden Helmet:120:0:textures/items/gold_helmet"
    - "315:0:1:Golden Chestplate:120:0:textures/items/gold_chestplate"
    - "316:0:1:Golden Leggings:120:0:textures/items/gold_leggings"
    - "317:0:1:Golden Boots:120:0:textures/items/gold_boots"
    - "298:0:1:Leather Cap:100:0:textures/items/leather_helmet"
    - "299:0:1:Leather Tunic:100:0:textures/items/leather_chestplate"
    - "300:0:1:Leather Pants:100:0:textures/items/leather_leggings"
    - "301:0:1:Leader Boots:100:0:textures/items/leather_boots"
  blocks:
    - "1:0:64:Stone:250:0:textures/blocks/stone"
    - "17:0:64:Oak Wood:250:0:textures/blocks/log_oak"
    - "20:0:64:Glass:250:0:textures/blocks/glass"
    - "24:0:64:Sandstone:250:0:textures/blocks/sandstone_normal"
    - "98:0:64:Stone Bricks:250:0:textures/blocks/stonebrick"
    - "155:0:64:Block of Quartz:250:0:textures/blocks/quartz_block_side"
    - "88:0:64:Snow:250:0:textures/blocks/snow"
    - "44:0:64:Stone Slab:250:0:textures/blocks/stone_slab_side"
    - "47:0:64:Bookshelf:250:0:textures/blocks/bookshelf"
  specials:
    - "466:0:1:Enchanted Apple:1000:1:https//www.digminecraft.com/food_recipes/images/golden_apple2.png"
    - "322:0:1:Golden Apple:300:1:https//www.digminecraft.com/food_recipes/images/golden_apple.png"
    - "396:0:1:Golden Carrot:100:1:https//www.digminecraft.com/food_recipes/images/golden_carrot.png"
  masks:
    - "397:0:1:Dragon Head:1000:1:https//img4.hostingpics.net/pics/436796skulldragon.png"
    - "397:0:1:Wither Skeleton Skull:500:1:https//img4.hostingpics.net/pics/826437skullwither.png"
    - "397:0:4:Creeper Head:200
0:1:https//img4.hostingpics.net/pics/556676skullcreeper.png"
    - "397:0:2:Zombie Head:100:1:https//img4.hostingpics.net/pics/415562skullzombie.png"
    - "307:0:3:Skeleton Head:100:1:https//img4.hostingpics.net/pics/589367skullskeleton.png"